f1 = open(r"C:\Users\ABHI\OneDrive\Documents\Desktop\AIAC\LAB 7.4\file.txt", "w")
f2 = open(r"C:\Users\ABHI\OneDrive\Documents\Desktop\AIAC\LAB 7.4\file.txt", "w")
f1.write("First file content\n")
f2.write("Second file content\n")
f1.close()
f2.close()
print("Files written successfully.")